# Glenn example batch script.
# see fwspider_tutor.pdf
# Everything else done prior to this
# because queue resources are not required
# negligible 
#PBS -N wet_LargeBox
#PBS -j oe
#PBS -m ae
#PBS -M gfm12@case.edu
#PBS -l walltime=01:00:00
#PBS -l nodes=2:ppn=8
#PBS -S /bin/bash
set -vx
# loading the modules
module load fftw3
module load gromacs-4.5.5

#the surface tension coupling is performed with an
#mdp option

# compute the surface parameter
# pass the filename as a variable into the surface parameter code
# by rewriting the file with a perl or pbs command
# OR.
# rewrite the surface parameter code to accept a flag with the filename
# as a variable. organize the filenames to be numbers between 1 and nmax (180?)
# then have the program rewrite the input.gro and output.bin, recompile, execute



# copying all files to nodes
pbsdcp *.* $TMPDIR
cd $TMPDIR
# PBS_O_WORKDIR refers to the directory from which the job was submitted.
cd $PBS_O_WORKDIR
# running the molecular dynamics
mpiexec mdrun_mpi -rdd 2.0 -s fws_em2.tpr -o fws_em.trr -c fws_b4pr.pdb -e em.edr -g em.log
# copying files back
pbsdcp -g fws_em.trr fws_b4pr.pdb em.edr em.log $PBS_O_WORKDIR
ls -al


