#PBS -N PE_10C_MS8ns
#PBS -j oe
#PBS -m abe
#PBS -M gfm12@case.edu
#PBS -l walltime=24:00:00
#PBS -l nodes=1:ppn=12
#PBS -S /bin/bash
set -vx
#for copying an entire subdirectory tree
cp -r /fs/lustre/cwr0408/1.3.2014/* /fs/lustre/cwr0408/1.29.2014/
#for copying a file into each of the polymer folders in a specific date folder
#echo PP6 PP24 PP18 PP15 PP12 PIB36 PIB24 PIB12 PE8 PE5 PE24 PE18 PE14 PE12 PE10 PE6 PP9 | xargs -n 1 cp ./EtOHMix100.pdb

