#PBS -N copeForPolyEthersFolders
#PBS -j oe
#PBS -m abe
#PBS -M gfm12@case.edu
#PBS -l walltime=24:00:00
#PBS -l nodes=1:ppn=12
#PBS -S /bin/bash
set -vx
cp -r /fs/lustre/cwr0408/1.3.2014/ /fs/lustre/cwr0408/Polyethers/*
cp -r /fs/lustre/cwr0408/12.20.2013/ /fs/lustre/cwr0408/Polyethers/*
cp -r /fs/lustre/cwr0408/11.29.2013/ /fs/lustre/cwr0408/Polyethers/*
cp -r /fs/lustre/cwr0408/8.26.2013/ /fs/lustre/cwr0408/Polyethers/*
cp -r /fs/lustre/cwr0408/8.8.2013/ /fs/lustre/cwr0408/Polyethers/*
cp -r /fs/lustre/cwr0408/9.9.2013/ /fs/lustre/cwr0408/Polyethers/*
cp -r /fs/lustre/cwr0408/9.5.2013/ /fs/lustre/cwr0408/Polyethers/*
cp -r /fs/lustre/cwr0408/9.3.2013/ /fs/lustre/cwr0408/Polyethers/*
cp -r /fs/lustre/cwr0408/9.2.2013/ /fs/lustre/cwr0408/Polyethers/*