#PBS -N PE_10C_MS8ns
#PBS -j oe
#PBS -m abe
#PBS -M gfm12@case.edu
#PBS -l walltime=24:00:00
#PBS -l nodes=1:ppn=12
#PBS -S /bin/bash
set -vx

X=Et
C=80
module load gromacs/4.6.3
for i in PE4 PE5 PE6 PE8 PE10 PE12 PE14 PE18 PE24 PP6 PP9 PP12 PP15 PP18 PIB12 PIB24 PIB36
do 
cd /fs/lustre/cwr0408/1.29.2014/$i
echo -e "1" | g_density -f md_concat.trr -s md1.tpr -o $X\OH$C\_$i\_density_$i\.xvg -dens mass -symm -d Z
echo -e "6" | g_density -f md_concat.trr -s md1.tpr -o $X\OH$C\_$i\_density_$C\OH.xvg -dens mass -symm -d Z
echo -e "5" | g_density -f md_concat.trr -s md1.tpr -o $X\OH$C\_$i\_density_HOH.xvg -dens mass -symm -d Z
echo -e "0" | g_density -f md_concat.trr -s md1.tpr -o $X\OH$C\_$i\_density_Sys.xvg -dens mass -symm -d Z
done